### ISSUE TITLE
Specifying Fine-grained Julia Versions

### ISSUE THREAD

**Issue by ninjin** [JuliaCI/travis-build#2]
Currently we only support `nightly` and `release`, both being the latest possible.  Ideally we should allow users to specify at least a release branch.  Should we also allow for minor as well as patch versions?  Would this be going overboard?

The implementation of all of the above should be fairly simply as long as we can have predictable URLs for all of the above versions.  Since earlier this month we have support for the [latest for the 0.3 release branch](https://github.com/travis-ci/travis-build/pull/318#issuecomment-66393339).

**Comment by ninjin** [comment]
I tend to agree with @tkelman, while it is true that we should stay compatible between patch versions, the best way to ensure that we are will be to allow testing for specific patch versions.

Thus I think our targets should be:

* nightly
* release (latest release)
* release-X
* release-X.Y
* release-X.Y.Z

**Comment by tkelman** [comment]
I'm not sure whether the `release-` prefix is necessary for specific version numbers?

**Comment by ninjin** [comment]
Excellent point, but are we really fine with specifying something like "1" at a later point?  Perhaps we should have a "v" prefix?

**Comment by tkelman** [comment]
> are we really fine with specifying something like "1" at a later point?

Sure, why not? That would mean the latest 1.x.

> Perhaps we should have a "v" prefix?

There's no "v" prefix for Ruby versions: http://docs.travis-ci.com/user/languages/ruby/#Choosing-Ruby-versions-and-implementations-to-test-against I'd rather leave it off if we don't need it.

I think we should keep "nightly" and "release" with their current meanings (probably adjust the links to point to S3 though), add "0.3", "0.4", and I'd personally vote for adding "0.3.5" and "0.3.4" and a few others if it doesn't get to be too much.

**Comment by tkelman** [comment]
And note that we've found very good use cases for wanting to test point releases. There have been cases of features getting backported to 0.3.4 that were not in 0.3.3 for example, where packages started taking advantage of these features and wound up broken for older releases of Julia if they didn't adjust the package's `REQUIRE` file accordingly. Backporting features is generally a bad idea for this reason, but it occasionally happens, and adding the capability to test against as many specific versions as we can easily support would be a good idea.

We don't have S3 links yet for 0.4-latest so right now that's only available via nightly. But once 0.4.0 gets released we should set that up. And maybe 0-latest which would currently point to 0.3-latest but would later point to 0.4-latest. Probably no need to worry about that one yet.

For now, I propose if the version number has 1 dot then translate to an S3 link for x.y-latest, if it has 2 dots then translate to an S3 link for the corresponding x.y.z release. We should be able to do this without hardcoding a list of acceptable version numbers I think.

**Comment by staticfloat** [comment]
I'm fine with Tony's proposal.  Let me know if there's anything that needs to change on the julia-hosting side.

**Comment by tkelman** [comment]
Hopefully there won't be. We haven't seen much of @ninjin in a little while, guess he's been busy.

It will probably need someone who knows ruby better than I do to implement the PR for this. Or I can stumble through it but it's not at the top of my list of things to do.

**Comment by ninjin** [comment]
@tkelman: I have had some health issues (buy me a non-sugary drink at JuliaCon and I will tell you all about it) and will be moving between continents.  However, I will see if I can start pushing this now that I have recovered from what I can recover from.

**Comment by tkelman** [comment]
@ninjin sorry to hear that, your health is much more important than silly open-source stuff... okarada o taisetsu ni

**Comment by stevengj** [comment]
At the very least, we need a way to test major releases prior to the current one.  Otherwise backwards compatibility is extremely difficult to maintain, and this will become more and more important as Julia matures (since we can no longer assume that the entire Julia universe upgrades as soon as a major release comes out).

**Comment by tkelman** [comment]
Could anyone review https://github.com/JuliaCI/travis-build/commit/96f45aa434bd3a9f7c358ccdff2549fe8746fff4 before I make an upstream PR out of that? Especially if you know any Ruby, cc @StefanKarpinski

**Comment by ninjin** [comment]
@tkelman: I have read through the logic a couple of times and it looks good to me.  There were only some minor design choice comments that could go either way really.

**Comment by tkelman** [comment]
Closed by https://github.com/travis-ci/travis-build/issues/487!
