### ISSUE TITLE
before_script suppresses default script?

### ISSUE THREAD

**Issue by wavexx** [JuliaCI/travis-build#3]
I've tried to use "before_script" to setup passwordless ssh access to localhost, as I normally did in Python. I'm not redefining the default "script" target, since I'm fine with the default.

See:

https://github.com/wavexx/Polyglot.jl/blob/1e324d3b30032a4f371d59f96054d1579e9e6167/.travis.yml

However, when I define before_script, it looks like the default Julia "script" is not run at all.
See the resulting build log:

https://travis-ci.org/wavexx/Polyglot.jl/jobs/64701128

**Comment by tkelman** [comment]
I don't know what would cause that. You might want to try `before_install` instead of `before_script`. Also this is an unofficial fork that's only really used for development of the Julia Travis setup, issue reports should go to https://github.com/travis-ci/travis-ci/issues

**Comment by wavexx** [comment]
On 05/30/2015 04:32 PM, Tony Kelman wrote:
> I don't know what would cause that. You might want to try
> `before_install` instead of `before_script`. Also this is an

Tried before_install and install as well, without change.

> unofficial fork that's only really used for development of the Julia
> Travis setup, issue reports should go to
> https://github.com/travis-ci/travis-ci/issues

Thanks for the tip.
Will re-open there.
